/* ═══════════════════════════════════════════════════════════════════════
   Æ T H E R  —  Env Injection Script
   ═══════════════════════════════════════════════════════════════════════
   Reads VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY from the
   environment and writes js/config.js for production deployment.
   Usage: node scripts/inject-env.mjs
   ═══════════════════════════════════════════════════════════════════════ */

import { writeFileSync, existsSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const URL = process.env.VITE_SUPABASE_URL;
const KEY = process.env.VITE_SUPABASE_ANON_KEY;

const EXAMPLE = resolve(ROOT, 'js/config.example.js');
const DEST = resolve(ROOT, 'js/config.js');

if (URL && KEY) {
  const content = `/* Auto-generated by scripts/inject-env.mjs */\nwindow.__SUPABASE_URL = ${JSON.stringify(URL)};\nwindow.__SUPABASE_ANON_KEY = ${JSON.stringify(KEY)};\n`;
  writeFileSync(DEST, content, 'utf-8');
  console.log('✓ js/config.js written from VITE_SUPABASE_URL/VITE_SUPABASE_ANON_KEY');
} else if (existsSync(EXAMPLE)) {
  // Fall back to example if env vars not set (local dev)
  const src = readFileSync(EXAMPLE, 'utf-8');
  writeFileSync(DEST, src, 'utf-8');
  console.log('✓ js/config.js copied from js/config.example.js (env vars not set)');
} else {
  console.error('✗ VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY not set, and no config.example.js found');
  process.exit(1);
}
