/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingHubRouteImport } from './routes/marketing-hub'
import { Route as IndexRouteImport } from './routes/index'

const MarketingHubRoute = MarketingHubRouteImport.update({
  id: '/marketing-hub',
  path: '/marketing-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketing-hub': typeof MarketingHubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketing-hub': typeof MarketingHubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketing-hub': typeof MarketingHubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/marketing-hub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/marketing-hub'
  id: '__root__' | '/' | '/marketing-hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingHubRoute: typeof MarketingHubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketing-hub': {
      id: '/marketing-hub'
      path: '/marketing-hub'
      fullPath: '/marketing-hub'
      preLoaderRoute: typeof MarketingHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingHubRoute: MarketingHubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
